### ISSUE TITLE
Qobuz cannot be downloaded

### ISSUE THREAD

**Issue by sn4000c** [jaylex32/BeatOn#3]
Deezer can download, Qobuz can search, but albums cannot be downloaded.thanks for sharing!

**Comment by jaylex32** [comment]
> Deezer can download, Qobuz can search, but albums cannot be downloaded.thanks for sharing!

can you provide a screenshot of what's the error or what you see?

**Comment by sn4000c** [comment]
[image: 1.png][image: 2.png]Thank you very much for your reply!

jaylex32 ***@***.***> 于2023年12月30日周六 11:32写道：

**Comment by jaylex32** [comment]
> Deezer can download, Qobuz can search, but albums cannot be downloaded.thanks for sharing!

You are not providing any information of what you are doing what error is giving you or the screens hot of the problem, I need more info to help you or fix the problem.
Thanks.

**Comment by sn4000c** [comment]
There is no error message, only the software download status column shows
failed. There was a problem with downloading BeatOn V2.0.1 about a week
before it was released. Maybe it's a problem with my network. thank you for
your reply!

jaylex32 ***@***.***> 于2024年1月2日周二 21:45写道：
