### ISSUE TITLE
some tracks in qobuz can't be downloaded

### ISSUE THREAD

**Issue by edgmkr** [jaylex32/BeatOn#4]
Hello @jaylex32  like said in the title, some tracks in qobuz can't be downloaded, sometimes it works, sometimes doesn't, may be it is a global problem or it's just me ? In general it takes 20-30 secondes then i see "failed" in downloads tab
![Capture d'écran 2024-06-10 015150](https://github.com/jaylex32/BeatOn/assets/163167484/b67ebd26-236f-461a-8051-869c8ae10aeb)

**Comment by jaylex32** [comment]
Closing
