### ISSUE TITLE
Can't Download From WebUI

### ISSUE THREAD

**Issue by animelol123** [jaylex32/BeatOn#5]
~~Whenever i try to download from the webui for beaton it just fails and in the program it doesn't say why it failed, any help would be appreciated~~

Edit: Missed the part where it says downloading from webui is for deezer only. Although i do want to ask now if there are any plans to make downloads work with qobuz?

**Comment by jaylex32** [comment]
> ~Whenever i try to download from the webui for beaton it just fails and in the program it doesn't say why it failed, any help would be appreciated~
> 
> Edit: Missed the part where it says downloading from webui is for deezer only. Although i do want to ask now if there are any plans to make downloads work with qobuz?

Yes, that is in my todo list, if you have any other suggestions or request let me know.
