### ISSUE TITLE
You're using our ARLs and tokens without permission

### ISSUE THREAD

**Issue by Firehawk52** [jaylex32/BeatOn#6]
Please remove all code scraping our website (https://rentry.co/firehawk52) or give full credit with link

**Comment by jaylex32** [comment]
> Please remove all code scraping our website (https://rentry.co/firehawk52) or give full credit with link
I specifically added it in the tooltip where the ARLs are coming from, if you hover the mouse over the "Get ARL" button. But yes, I will add full credit to you for the ARLs here, thanks for your amazing website.
