### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by Adouche-off** [jaylex32/BeatOn#8]
_Hello,_
I tried to download my Deezer playlist with BeatOn, but there's one song that didn't download properly.
[Here's the output (found in "temp" file).](https://github.com/user-attachments/files/16663888/Here.s.the.output.zip)
It's a song that I added with the _upload MP3_ feature in Deezer, I think this is why it's corrupted. I hope you can fix this issue.

_**Adouche**_

**Comment by jaylex32** [comment]
> _Hello,_ I tried to download my Deezer playlist with BeatOn, but there's one song that didn't download properly. [Here's the output (found in "temp" file).](https://github.com/user-attachments/files/16663888/Here.s.the.output.zip) It's a song that I added with the _upload MP3_ feature in Deezer, I think this is why it's corrupted. I hope you can fix this issue.
> 
> _**Adouche**_

I don't think that can be fixed at this time. The reason it's probably not downloading correctly is that Deezer doesn't have metadata for it, so the program doesn't know what to do with it. If the file plays and there are no audio problems with it, then it's not corrupt; it just doesn't have metadata.

**Comment by Adouche-off** [comment]
Thank you. You can just add the original file, so that's not very important.
