### ISSUE TITLE
Re BeatOn

### ISSUE THREAD

**Issue by PompeyMark** [jaylex32/BeatOn#9]
Hi ....i have installed Beat On but somehow it only seems to download 10 or so seconds of each track on Qobuz... when i select Deezer all downloads fail
Please can you tell me the correct way to install this great programme
Cheers
Tank You

**Comment by jaylex32** [comment]
First, for Deezer you need a arl, if you press the button that said arl, you can get a random one then after you get the arl it will show in the deezer settings, press save and after that it should work if not restart the program, now for Qobuz you need a user_auth and a user_id, once you get that you press where it said retrieve Qobuz credentials then after that save, try it and if doesn't work restart the program, the user_id and auth, you going to have to get a own account or look somewhere for it, the one that is included is just a demo account.

**Comment by edgmkr** [comment]
I successfully configured both (Deezer and Qobuz). Deezer works, Qobuz: the songs are all 30 seconds long, maybe because my Qobuz account does not have a paid subscription

**Comment by jaylex32** [comment]
> I successfully configured both (Deezer and Qobuz). Deezer works, Qobuz: the songs are all 30 seconds long, maybe because my Qobuz account does not have a paid subscription

That's exactly what it is, you can find one really easily if you look in the correct place, read the Readme in the program and you can find it right a way.

**Comment by PompeyMark** [comment]
Hi Everyone
Thank you for help......I still carnt configure anything .maybe its me but will keep trying
Cheers all
Regards
Mark

**Comment by edgmkr** [comment]
@jaylex32 I found what I need in readme, thanks for your help. Qobuz works too!
